# pytorch_lightning==1.8.0
seed_everything: 42
trainer:
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: /scratch/kys2020/climateML/regional_forecast_their_climax2/logs
      name: null
      version: null
      log_graph: false
      default_hp_metric: true
      prefix: ''
      sub_dir: null
      comment: ''
      purge_step: null
      max_queue: 10
      flush_secs: 120
      filename_suffix: ''
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: /scratch/kys2020/climateML/regional_forecast_their_climax2/checkpoints
      filename: epoch_{epoch:03d}
      monitor: val/w_rmse
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: false
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val/w_rmse
      min_delta: 0.0
      patience: 5
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: null
      log_rank_zero_only: false
  - class_path: pytorch_lightning.callbacks.RichModelSummary
    init_args:
      max_depth: -1
  - class_path: pytorch_lightning.callbacks.RichProgressBar
    init_args:
      refresh_rate: 1
      leave: false
      theme:
        description: white
        progress_bar: '#6206E0'
        progress_bar_finished: '#6206E0'
        progress_bar_pulse: '#6206E0'
        batch_progress: white
        time: grey54
        processing_speed: grey70
        metrics: white
      console_kwargs: null
  default_root_dir: /scratch/kys2020/climateML/regional_forecast_their_climax2
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  devices: '2'
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 5
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  log_every_n_steps: 50
  accelerator: gpu
  strategy: ddp
  sync_batchnorm: true
  precision: 16
  enable_model_summary: true
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true
model:
  net:
    class_path: climax.regional_forecast.arch.RegionalClimaX
    init_args:
      default_vars:
      - land_sea_mask
      - orography
      - lattitude
      - 2m_temperature
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind
      - geopotential_50
      - geopotential_250
      - geopotential_500
      - geopotential_600
      - geopotential_700
      - geopotential_850
      - geopotential_925
      - u_component_of_wind_50
      - u_component_of_wind_250
      - u_component_of_wind_500
      - u_component_of_wind_600
      - u_component_of_wind_700
      - u_component_of_wind_850
      - u_component_of_wind_925
      - v_component_of_wind_50
      - v_component_of_wind_250
      - v_component_of_wind_500
      - v_component_of_wind_600
      - v_component_of_wind_700
      - v_component_of_wind_850
      - v_component_of_wind_925
      - temperature_50
      - temperature_250
      - temperature_500
      - temperature_600
      - temperature_700
      - temperature_850
      - temperature_925
      - relative_humidity_50
      - relative_humidity_250
      - relative_humidity_500
      - relative_humidity_600
      - relative_humidity_700
      - relative_humidity_850
      - relative_humidity_925
      - specific_humidity_50
      - specific_humidity_250
      - specific_humidity_500
      - specific_humidity_600
      - specific_humidity_700
      - specific_humidity_850
      - specific_humidity_925
      img_size:
      - 32
      - 64
      patch_size: 2
      embed_dim: 1024
      depth: 8
      decoder_depth: 2
      num_heads: 16
      mlp_ratio: 4
      drop_path: 0.1
      drop_rate: 0.1
  pretrained_path: /scratch/kys2020/climateML/checkpoints/their_model2/epoch_004.ckpt
  lr: 5.0e-07
  beta_1: 0.9
  beta_2: 0.99
  weight_decay: 1.0e-05
  warmup_epochs: 10000
  max_epochs: 100000
  warmup_start_lr: 1.0e-08
  eta_min: 1.0e-08
data:
  root_dir: /scratch/kys2020/climateML/ERA5/5.625deg_npz
  variables:
  - land_sea_mask
  - orography
  - lattitude
  - 2m_temperature
  - 10m_u_component_of_wind
  - 10m_v_component_of_wind
  - geopotential_50
  - geopotential_250
  - geopotential_500
  - geopotential_600
  - geopotential_700
  - geopotential_850
  - geopotential_925
  - u_component_of_wind_50
  - u_component_of_wind_250
  - u_component_of_wind_500
  - u_component_of_wind_600
  - u_component_of_wind_700
  - u_component_of_wind_850
  - u_component_of_wind_925
  - v_component_of_wind_50
  - v_component_of_wind_250
  - v_component_of_wind_500
  - v_component_of_wind_600
  - v_component_of_wind_700
  - v_component_of_wind_850
  - v_component_of_wind_925
  - temperature_50
  - temperature_250
  - temperature_500
  - temperature_600
  - temperature_700
  - temperature_850
  - temperature_925
  - relative_humidity_50
  - relative_humidity_250
  - relative_humidity_500
  - relative_humidity_600
  - relative_humidity_700
  - relative_humidity_850
  - relative_humidity_925
  - specific_humidity_50
  - specific_humidity_250
  - specific_humidity_500
  - specific_humidity_600
  - specific_humidity_700
  - specific_humidity_850
  - specific_humidity_925
  buffer_size: 10000
  out_variables:
  - geopotential_500
  - temperature_850
  - 2m_temperature
  region: NorthAmerica
  predict_range: 72
  hrs_each_step: 1
  batch_size: 16
  num_workers: 1
  pin_memory: false
